version: 2

sources:
  - name: subway_data
    meta:
      external_location: "/Users/juanherrera/Desktop/nyc-subway-analytics/data/subway_data/mta_subway_complete_2024/*.parquet"
    tables: 
      - name: mta_subway_complete_2024
        description: Raw MTA ridership data from NY.gov API